//
//  UsefulVals.swift
//  Chess
//
//  Created by William Becht on 3/13/22.
//

import Foundation


var chosenFont = "SinhalaSangamMN-Bold"

var lastScene = ""

var curSceneNext = ""

var opponentAutoMoves = true

var chosenLevel = 0

var lives = 3

var boardMult = 1.0
var boardMult2 = 0.8

var filesDict = ["London System":londonFiles, "Caro-Kann":[String](), "Slav":[String](),"Queen's Gambit":[String]()]

let openingsList = ["London System","Queen's Gambit"]
let defensesList = ["Caro-Kann","Slav"]


var londonFiles_Depth3 = ["FenFiles/London_Depth3/London_d4d5Bf4_Depth3_RM5_output1",
                          "FenFiles/London_Depth3/London_d4d5Bf4_Depth3_RM5_output2",
                          "FenFiles/London_Depth3/London_d4d5Bf4_Depth3_RM5_output3",
                          "FenFiles/London_Depth3/London_d4d5Bf4_Depth3_RM5_output4",
                          "FenFiles/London_Depth3/London_d4d5Bf4_Depth3_RM5_output5"]

var londonFiles_Depth4 = ["FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output1",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output2",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output3",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output4",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output5",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output6",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output7",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output8",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output9",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output10",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output11",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output12",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output13",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output14",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output15",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output16",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output17",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output18",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output19",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output20",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output21",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output22",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output23",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output24",
                          "FenFiles/London_Depth4/London_d4d5Bf4_Depth4_RM5_output25"]

var londonFiles_Depth5 = ["FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output1",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output2",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output3",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output4",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output5",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output6",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output7",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output8",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output9",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output10",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output11",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output12",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output13",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output14",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output15",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output16",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output17",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output18",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output19",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output20",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output21",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output22",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output23",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output24",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output25",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output26",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output27",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output28",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output29",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output30",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output31",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output32",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output33",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output34",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output35",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output36",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output37",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output38",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output39",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output40",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output41",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output42",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output43",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output44",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output45",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output46",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output47",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output48",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output49",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output50",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output51",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output52",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output53",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output54",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output55",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output56",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output57",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output58",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output59",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output60",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output61",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output62",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output63",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output64",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output65",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output66",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output67",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output68",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output69",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output70",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output71",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output72",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output73",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output74",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output75",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output76",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output77",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output78",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output79",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output80",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output81",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output82",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output83",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output84",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output85",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output86",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output87",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output88",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output89",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output90",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output91",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output92",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output93",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output94",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output95",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output96",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output97",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output98",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output99",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output100",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output101",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output102",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output103",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output104",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output105",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output106",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output107",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output108",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output109",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output110",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output111",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output112",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output113",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output114",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output115",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output116",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output117",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output118",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output119",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output120",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output121",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output122",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output123",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output124",
                          "FenFiles/London_Depth5/London_d4d5Bf4_Depth5_RM5_output125"]

var londonFiles_Depth6 = ["FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output1",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output2",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output3",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output4",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output5",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output6",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output7",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output8",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output9",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output10",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output11",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output12",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output13",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output14",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output15",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output16",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output17",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output18",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output19",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output20",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output21",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output22",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output23",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output24",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output25",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output26",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output27",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output28",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output29",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output30",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output31",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output32",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output33",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output34",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output35",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output36",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output37",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output38",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output39",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output40",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output41",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output42",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output43",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output44",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output45",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output46",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output47",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output48",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output49",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output50",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output51",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output52",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output53",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output54",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output55",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output56",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output57",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output58",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output59",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output60",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output61",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output62",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output63",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output64",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output65",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output66",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output67",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output68",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output69",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output70",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output71",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output72",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output73",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output74",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output75",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output76",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output77",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output78",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output79",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output80",
                   "FenFiles/London_Depth6/London_d4d5Bf4_Depth6_RM3_output81"]

var londonFiles_Depth7 = ["FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output1",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output2",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output3",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output4",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output5",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output6",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output7",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output8",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output9",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output10",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output11",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output12",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output13",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output14",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output15",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output16",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output17",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output18",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output19",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output20",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output21",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output22",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output23",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output24",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output25",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output26",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output27",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output28",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output29",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output30",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output31",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output32",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output33",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output34",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output35",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output36",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output37",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output38",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output39",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output40",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output41",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output42",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output43",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output44",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output45",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output46",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output47",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output48",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output49",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output50",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output51",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output52",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output53",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output54",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output55",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output56",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output57",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output58",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output59",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output60",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output61",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output62",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output63",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output64",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output65",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output66",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output67",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output68",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output69",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output70",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output71",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output72",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output73",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output74",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output75",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output76",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output77",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output78",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output79",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output80",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output81",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output82",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output83",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output84",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output85",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output86",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output87",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output88",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output89",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output90",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output91",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output92",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output93",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output94",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output95",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output96",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output97",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output98",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output99",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output100",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output101",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output102",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output103",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output104",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output105",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output106",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output107",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output108",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output109",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output110",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output111",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output112",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output113",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output114",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output115",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output116",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output117",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output118",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output119",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output120",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output121",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output122",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output123",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output124",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output125",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output126",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output127",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output128",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output129",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output130",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output131",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output132",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output133",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output134",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output135",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output136",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output137",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output138",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output139",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output140",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output141",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output142",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output143",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output144",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output145",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output146",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output147",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output148",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output149",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output150",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output151",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output152",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output153",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output154",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output155",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output156",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output157",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output158",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output159",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output160",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output161",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output162",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output163",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output164",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output165",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output166",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output167",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output168",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output169",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output170",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output171",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output172",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output173",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output174",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output175",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output176",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output177",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output178",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output179",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output180",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output181",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output182",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output183",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output184",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output185",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output186",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output187",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output188",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output189",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output190",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output191",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output192",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output193",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output194",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output195",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output196",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output197",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output198",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output199",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output200",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output201",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output202",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output203",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output204",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output205",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output206",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output207",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output208",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output209",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output210",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output211",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output212",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output213",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output214",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output215",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output216",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output217",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output218",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output219",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output220",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output221",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output222",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output223",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output224",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output225",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output226",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output227",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output228",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output229",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output230",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output231",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output232",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output233",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output234",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output235",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output236",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output237",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output238",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output239",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output240",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output241",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output242",
                          "FenFiles/London_Depth7/London_d4d5Bf4_Depth7_RM3_output243"]

/*
var londonFiles = ["testEnPassantQueening_output",
                   "FenFiles/London System/testCastleShort_output",
                   "FenFiles/London System/testCastleLong_output",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn1",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn2",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn3",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn4",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn5",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn6",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn7",
                   "FenFiles/London System/NC4_Blunder/TXT/LondonSystem_NC4Blunder_pgn8"]
*/


//var londonFiles = ["FenFiles/London System/testCastleShort_output","FenFiles/London System/testCastleLong_output"]

// --------------- London System ---------------
// 1st Move Branch: 1. d4  d5
    // 2. bf4 nc6
        // 3. e3 nf6
            // 4. nd2 bg4
                // 5. be2
                // 5. be2
                // 5. be2
            // 4. nd2 ne4
                // 5. nxe4
                // 5. nxe4
                // 5. nxe4
            // 4. nd2 bf5
                // 5. nf3
                // 5. nf3
                // 5. nf3



        // 3. e3 bf5
            // 4. c4 dxc4
            // 4. c4 e6
        // 3. e3 e6
            // 4. nf3 nf6
            // 4. nf3 bd6

// ^^^^^^^^^ FINISH THIS FIRST ^^^^^^^^^ //

    // 2. bf4 nf6
        // 3.
        // 3.
        // 3.
    // 2. bf4 e6
        // 3.
        // 3.
        // 3.
    // 2. bf4 bf5
        // 3.
        // 3.
        // 3.
    // 2. bf4 nc5
        // 3.
        // 3.
        // 3.

// 2nd Move Branch: 1. d4 e6
    // 2.

// 3rd Move Branch: 1. d4 nf6
    // 2.


// ---------------------------------------------
var londonFiles = londonFiles_Depth3 + londonFiles_Depth4 + londonFiles_Depth5 + londonFiles_Depth6 + londonFiles_Depth7
var highScore = 0

var caroKannFiles = [""]

var curFileList = londonFiles
var curTitle = ""
